### ISSUE TITLE
Error: useRootStore must be used within RootStoreProvider

### ISSUE THREAD

**Issue by vladles** [ivandotv/mobx-nextjs-root-store#40]
If you want to use **RootStoreProvider** on page ( /home for example) after launching "npm run build" you facing with the error that _**useRootStore must be used within RootStoreProvider**_.
But if you define RootStoreProvider in _app.js - everything is work.

**Comment by ivandotv** [comment]
Yes, you can't use the root store outside of the root provider.

**Comment by vladles** [comment]
Yes, correct. 
But I mean that, we can use < RootStoreProvider /> just in _app.js.

And if we want to place this Provider to /pages/blog/index.js 
we faced error

**Comment by ivandotv** [comment]
yes you can put `<RootStoreProvider />` in `_app.js`

**Comment by vladles** [comment]
What if I want to place and provide RootStoreProvider just for one page? 
I correct understood that this is unpossible?

**Comment by ivandotv** [comment]
The main point is you can only use the root store hook if you have the root store provider component somewhere higher up the component tree.

**Comment by vladles** [comment]
Ok, got you, thank you!
